version: '3.7'

services:
  wp_thilak:
    image: wordpress:php7.3-fpm
    container_name: wp_thilak
    volumes:
      - wp_thilak_data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - wp_thilak_net
    restart: always

networks:
  wp_thilak_net:
    name: wp_thilak_net